https://github.com/learnpack/learnpack/issues/561
4GeeksAcademy/html-tutorial-exercises-course pull request #46
Opened 2021-12-13 17:04 UTC by ElviraQDP

changing images paths from absolute to relative and fixing layout

2021-12-13 19:37 UTC, tommygonzaleza approved these changes

2021-12-14 16:22 UTC, alesanchezr approved these changes

2022-01-17 19:27 UTC, tommygonzaleza requested changes

2022-01-17 19:27 UTC, tommygonzaleza commented on exercises/05-create-anchors/README.es.md
> +![Link url](http://i.imgur.com/GGj8vBu.png)
Add this image to the repository and use the relative path

2022-01-17 19:27 UTC, tommygonzaleza commented on exercises/05-create-anchors/README.md
> +![Link url](http://i.imgur.com/GGj8vBu.png)
Add this image to the repository and use the relative path

2022-01-19 19:34 UTC, tommygonzaleza approved these changes

2022-01-19 19:34 UTC, merged